INSERT INTO EVENTO (ID_EVENTO, NOMBRE_EVENTO, FECHA_INICIO_EVENTO, LOCALIDAD) 
VALUES (1,'San Breixo', '2014-10-15','Barro, Pontevedra');
INSERT INTO EVENTO (ID_EVENTO, NOMBRE_EVENTO, FECHA_INICIO_EVENTO, LOCALIDAD) 
VALUES (2,'San Froilan','2014-10-15','Plaza Aguas Ferreas, Lugo');

INSERT INTO MUSICO (ID_MUSICO, NOMBRE_MUSICO, DIRECCION, INSTRUMENTO) 
VALUES (1,'Pedro Lopez','Direccion de Pedro','Guitarra');
INSERT INTO MUSICO (ID_MUSICO, NOMBRE_MUSICO, DIRECCION, INSTRUMENTO) 
VALUES (2,'Juan Rodriguez','Direccion de Juan','Bajo');
INSERT INTO MUSICO (ID_MUSICO, NOMBRE_MUSICO, DIRECCION, INSTRUMENTO) 
VALUES (3,'Ana','Direccion de Ana','Teclado');
INSERT INTO MUSICO (ID_MUSICO, NOMBRE_MUSICO, DIRECCION, INSTRUMENTO) 
VALUES (4,'Alvaro','Direccion de Pedro','Bateria');

INSERT INTO GRUPO (ID_GRUPO, NOMBRE_ORQUESTA, SALARIO_ACTUACION) 
VALUES (1,'Combo Dominicano',5000);

INSERT INTO MUSICO_GRUPO (ID_MUSICO_GRUPO, ID_MUSICO, ID_GRUPO) 
VALUES (1, 1, 1);
INSERT INTO MUSICO_GRUPO (ID_MUSICO_GRUPO, ID_MUSICO, ID_GRUPO) 
VALUES (2, 2, 1);
INSERT INTO MUSICO_GRUPO (ID_MUSICO_GRUPO, ID_MUSICO, ID_GRUPO) 
VALUES (3, 3, 1);
INSERT INTO MUSICO_GRUPO (ID_MUSICO_GRUPO, ID_MUSICO, ID_GRUPO) 
VALUES (4, 4, 1);

INSERT INTO GRUPO_EVENTO (ID_GRUPO_EVENTO, FECHA_ACTUACION, ID_EVENTO, ID_GRUPO)
VALUES (1, '2014-10-15', 1, 1);
INSERT INTO GRUPO_EVENTO (ID_GRUPO_EVENTO, FECHA_ACTUACION, ID_EVENTO, ID_GRUPO)
VALUES (2, '2014-11-12', 1, 1);